// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFuCqJJLOaf0dLgOm8XD4XQ8rQ9SYsCM',
    appId: '1:534139909428:android:281235a637392be4f5e161',
    messagingSenderId: '534139909428',
    projectId: 'marriagephrasebook',
    storageBucket: 'marriagephrasebook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0hyi_uXxykq8cydgTZe1ohv8n_Qfn66s',
    appId: '1:534139909428:ios:b7868910f7129081f5e161',
    messagingSenderId: '534139909428',
    projectId: 'marriagephrasebook',
    storageBucket: 'marriagephrasebook.appspot.com',
    iosClientId: '534139909428-37lk9geniee66tee1o8naf6rjd0eshqd.apps.googleusercontent.com',
    iosBundleId: 'com.krzysztofwozniak.marriagephrasebook',
  );
}
